### ISSUE TITLE
Drag from one file to another in split panes

### ISSUE THREAD

**Issue by keithjgrant** [geoffthibeau/simple-drag-drop-text#11]
Thanks for this package!

This issue is similar to issue #6, but hopefully(?) easier to implement. I often develop with two side-by-side panes in Atom. I would love to be able to drag from the file on one side into the other. I do this all the time  when refactoring, and was disappointed to discover Atom doesn't do it.

**Comment by geoffthibeau** [comment]
Enhancements will not be added to this plugin, as [Github plans to sunset Atom by the end of this year](https://github.blog/2022-06-08-sunsetting-atom/).
