### ISSUE TITLE
Drag and drop from line number

### ISSUE THREAD

**Issue by joshuaneedham** [geoffthibeau/simple-drag-drop-text#12]
I am curious if it's possible to add the functionality of drag and drop to the line number without having to hover selected text? Currently if I click on a line number the entire line is selected however I have to move the cursor right toward the text in order to drag and drop.

**Comment by mark-hahn** [comment]
It is definitely possible with a moderate amount of work.

> however I have to move the cursor right toward the text in order to drag
> and drop

This isn't a big burden (grin) but I know every little motion adds up as
you work all day.

I'm not sure I'd ever get around to doing this.  Feel free to take a stab
and do it yourself.  It could even be a separate package if you wish and
not interfere with this one.

**Comment by joshuaneedham** [comment]
Right on. Just wondered if it was in this packages future. Thanks for your contributions!
