### ISSUE TITLE
Broken with highlight-selected

### ISSUE THREAD

**Issue by ghost** [geoffthibeau/simple-drag-drop-text#18]
I had to disable hightlight-selected to get it more or less work. Drag n Drop behavior is still unreliable. Is it possible to make it compatible with highlight-selected?

https://atom.io/packages/highlight-selected

**Comment by geoffthibeau** [comment]
There is no plan to improve interoperability with other Atom packages, as [Github has chosen to sunset Atom by the end of this year](https://github.blog/2022-06-08-sunsetting-atom/).
