### ISSUE TITLE
atom-text-editor.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by vnt** [geoffthibeau/simple-drag-drop-text#19]
The contents of `atom-text-editor` elements are no longer encapsulated
within a shadow DOM boundary. Please, stop using `shadowRoot` and access
the editor contents directly instead.
```
atom-text-editor.Object.defineProperty.get (/Applications/WebDesign/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-element.js:58:18)
<unknown> (/Users/vnt/.atom/packages/simple-drag-drop-text/lib/simple-drag-drop-text.coffee:58:26)
_combinedTickCallback (internal/process/next_tick.js:67:7)
process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by johnathan99j** [comment]
This is being discussed at #23

**Comment by riclf** [comment]
On Atom 1.13.0 I'm still getting 2 issues about shadowRoot even though I had Disabled the Plugin, the Deleted it, and finally re-acquired it via the Atom Plugin Install.  No complaints, just a FYI.  -Ric

**Comment by Oblik-Design** [comment]
same error still, please update it, it's a great addition to Atom.

**Comment by tp00012x** [comment]
The contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. Please, stop using shadowRoot and access the editor contents directly instead.
Report Issue
atom-text-editor.Object.defineProperty.get - /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:68:18
<unknown> - /Users/anthonyptorres/.atom/packages/simple-drag-drop-text/lib/simple-drag-drop-text.coffee:58:26
_combinedTickCallback - internal/process/next_tick.js:67:7
process._tickCallback - internal/process/next_tick.js:98:9
The contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. Please, stop using shadowRoot and access the editor contents directly instead.
Report Issue
atom-text-editor.Object.defineProperty.get - /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:68:18
<unknown> - /Users/anthonyptorres/.atom/packages/simple-drag-drop-text/lib/simple-drag-drop-text.coffee:59:38
_combinedTickCallback - internal/process/next_tick.js:67:7
process._tickCallback - internal/process/next_tick.js:98:9

**Comment by GeorgeWL** [comment]
@tp00012x we know, see #23

**Comment by geoffthibeau** [comment]
I've taken over as maintainer of this package. Please update to 0.3.4 (you should see an available update for this package in Atom).
