### ISSUE TITLE
Issue with triple-click

### ISSUE THREAD

**Issue by mischnu** [geoffthibeau/simple-drag-drop-text#21]
There is little trouble with marking more than one paragraph (at least on macOS). I used to do this by **triple-clicking** and holding the mouse button somwhere in the text of the first line and then move down to the last line. The triple-click ensures that the whole paragraph is marked including the line break at the end.

However, with simple-drag-drop-text the whole paragraph is displayed as marked after the triple-click but as soon as you move the mouse, you only drag the word where your cursor has been when doing the clicks.

Know what I mean? Hope I could explain this quite understandable…

**Comment by geoffthibeau** [comment]
Sounds related to #5 . I'm on Mac but haven't used this method of moving text before.

Can you perform this in TextEdit or another Mac program? Maybe I'm not clicking correctly.

What *does* work is triple-clicking to select a paragraph, then a separate click-drag to move the paragraph. But it sounds like you're expecting the original triple-click to carry a drag feature with it.

Please confirm. Thanks.

**Comment by mvanlammeren** [comment]
It is a long-standing UX on the Mac to triple-click and drag to select blocks of text. In fact, I noticed that this was "broken" within 30 seconds of installing simple-drag-drop-text.

You can try this UX feature in almost any Mac application, including Notes, TextEdit, or right on this page in a web browser.

Single-click and drag: selects from first cursor position to second cursor position
Double-click and drag: selects entire word, and highlights words as the cursor moves
Triple-click and drag: selects entire paragraph and highlights paragraphs as the cursor moves

Trivia -- Going back to the 1980s and 1990s, ClarisWorks also supported quadruple-click and drag, where triple-click selected a soft-wrapped line and quadruple-click selected a paragraph, but I don't know of any other editors that worked that way.

If you fix this, then I will re-install simple-drag-drop-text in a heartbeat. Thanks!

**Comment by geoffthibeau** [comment]
Resolved with v0.5.0.
2c75449e4924e08b30c40229916f49311a613aae
