### ISSUE TITLE
Deprecated calls in new Atom versions

### ISSUE THREAD

**Issue by Sogl** [geoffthibeau/simple-drag-drop-text#23]
Hello!

What I see in last Atom v. 1.13.0 ia32:
![image](https://cloud.githubusercontent.com/assets/7556290/21869732/17b77ff2-d8ad-11e6-828f-58b4c091a4ea.png)

Is it possible to update the plugin?

**Comment by mark-hahn** [comment]
I'm sorry but I don't have the time to work on atom projects right now.  I
would be happy if someone else could take over ownership of any or all.

**Comment by geoffthibeau** [comment]
@Sogl The coffee file is linked in that deprecation warning. Click it and modify the coffee file to remove the deprecation warning.

A quick test that seems to be working: within the `setEditor` method, remove/comment the `@lines.shadowRoot` stuff.

Here is a paste of what you can replace `setEditor` with:
```
  setEditor: ->
    process.nextTick =>
      if not (@editor = atom.workspace.getActiveTextEditor())
        @clear()
        return

      @linesSubs?.dispose()
      @lines = atom.views.getView(@editor)
      @lines = @lines.querySelector '.lines'
      @linesSubs = new SubAtom
      @linesSubs.add @lines, 'mousedown', (e) => @mousedown e
      @linesSubs.add @lines, 'mousemove', (e) =>
        if @mouseIsDown and e.which > 0 then @drag() else @clear()
```

Indentation matters. Atom will let you know if you've got something wrong.

**Comment by mark-hahn** [comment]
If I give you ownership of the package can you implement this?  I joined a
start-up and I have almost zero hours a day free.

**Comment by Jany-M** [comment]
As @geoffthibeau pointed out, the only change is commenting out the line of code that use `shadowRoot` and simply leaving `@lines = @lines.querySelector '.lines'` as the only line among those.
Fixes the deprecation notice and the package works fine.
Maybe a Pull Request?

@mark-hahn it really is a super fast fix, whenver you could manage.

**Comment by GeorgeWL** [comment]
@mark-hahn has anyone taken you up on the sharing ownership yet?

I'm personally a bit too junior in skill I think to deal with the amount of work this project has, but would love to see it updated.

**Comment by mark-hahn** [comment]
On Wed, Feb 8, 2017 at 6:07 AM, George W Langham <notifications@github.com>
wrote:

> has anyone taken you up on the sharing ownership yet?
>
>
No.  So you taking over ownership would be an improvement no matter what
your skill level.  :-)

**Comment by riclf** [comment]
@mark-hahn I have never even seen a coffee source file, or I would bite for the community. But in the time it takes to respond here you could make the change that @Jany-M has suggested. PLEASE. Do I need to send you a pizza? ;)

**Comment by mark-hahn** [comment]
It's not a matter of just working on it.  I don't have any dev tools set up
for it.  I've switched to working on embedded systems.  I don't even
remember at the moment what the process is for releasing packages.

**Comment by geoffthibeau** [comment]
@mark-hahn I'll do it. What's the process to transfer ownership?

**Comment by mark-hahn** [comment]
First you have to delete any repo with the same name.  Save your copy
somewhere.

**Comment by geoffthibeau** [comment]
@mark-hahn Sorry. It's deleted now. I also looked up the transfer help doc so I'll look out for the email once you process it. Thanks!

**Comment by Sogl** [comment]
@geoffthibeau Thx for the fix!
Now you also plugin/repository owner. Surprisingly :smile:

**Comment by riclf** [comment]
@geoffthibeau I would like to express my appreciation to you too. Your effort to the community is recognized. And @mark-hahn, I would like to thank you for the original work. It has been very useful. Your willingness to let another dev in to fix the code is worthy of thanks too. Thank you both.

Coding on-wards!

**Comment by mark-hahn** [comment]
> I would like to express my appreciation

Ditto.  I also have 19 other packages that need loving.  Hint hint.
