### ISSUE TITLE
atom-text-editor.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by Seralto** [geoffthibeau/simple-drag-drop-text#26]
The contents of `atom-text-editor` elements are no longer encapsulated
within a shadow DOM boundary. Please, stop using `shadowRoot` and access
the editor contents directly instead.
```
atom-text-editor.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:68:18)
<unknown> (/Users/toledos/.atom/packages/simple-drag-drop-text/lib/simple-drag-drop-text.coffee:58:26)
_combinedTickCallback (internal/process/next_tick.js:67:7)
process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by geoffthibeau** [comment]
@Seralto Yesterday the original author gave ownership of the package to me. I've pushed an update (0.3.4) this morning that should resolve your issue.

Related: #19, #23, #25

**Comment by Seralto** [comment]
Dear @geoffthibeau, problem solved.
Many thanks.
