### ISSUE TITLE
Drag and Drop Not Working

### ISSUE THREAD

**Issue by midwestocean** [geoffthibeau/simple-drag-drop-text#28]
I'm no longer able to use the drag and drop. It started about 1-2 weeks ago. No matter how long I hold down or where I try to click on the highlighted text, or even when holding down Ctrl, it will just start selecting text again as soon as I move the mouse. 

I'm also no longer able to drag text from other sources and drop it onto a file in atom, so it's possible the problem is with Atom itself. I just discovered this, so I'm still looking around to see if it's a known issue.

I've tried uninstalling and reinstalling the plugin, but it did not make a difference. I also tried the drag-drop-text sister package, which works, but I really dislike the implementation. 

Apart from the above, I haven't made any changes to my plugin list in a few months, though I do keep up with package updates. 

If there's any other information that may help with troubleshooting, please let me know.

plugin v0.3.4
atom v1.8.0
os: Ubuntu 16.04.1
desktop: xfce v4.12

Thanks,
-mwo

**Comment by geoffthibeau** [comment]
@midwestocean Are you able to update Atom to the latest release? It could be that the change in 1.13.0 (removing shadowRoot) is not backwards compatible.

**Comment by midwestocean** [comment]
That did it, thank you! I completely forgot don't have a ppa for atom so it doesn't update through apt. I assumed it was already at the newest version. No matter how long I code, I guess I'll always have to relearn the "never assume" lesson every now and again.  : \
