### ISSUE TITLE
atom-text-editor.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by brunnobb** [geoffthibeau/simple-drag-drop-text#29]
The contents of `atom-text-editor` elements are no longer encapsulated
within a shadow DOM boundary. Please, stop using `shadowRoot` and access
the editor contents directly instead.
```
atom-text-editor.Object.defineProperty.get (C:\Users\brunn\AppData\Local\atom\app-1.14.3\resources\app.asar\src\text-editor-element.js:68:18)
<unknown> (C:\Users\brunn\.atom\packages\simple-drag-drop-text\lib\simple-drag-drop-text.coffee:58:26)
_combinedTickCallback (internal/process/next_tick.js:67:7)
process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by geoffthibeau** [comment]
@brunnobb Have you updated this plugin to the latest version? I believe we've fixed this deprecation.

Please confirm which version of simple-drag-drop-text you are using. Thanks!
