### ISSUE TITLE
update broke plugin on Atom beta

### ISSUE THREAD

**Issue by noseGoblin** [geoffthibeau/simple-drag-drop-text#30]
The recent 2/9/17 update has completely disabled this plugin for me, which I use constantly. It's driving me crazy. I love this tool, so somebody please fix this.

I am on Atom beta ver 1.9.0-beta1

My package ver is 0.3.4, but it looks like Feb 9th there were 3 version updates, so I don't know what happened. All I know is I have tried a lot of renaming, reinstalling, deleting re-this re-that and nothing is bringing back that functionality I lost.

Please help!
Sad Code Monkey

**Comment by geoffthibeau** [comment]
@noseGoblin Are you able to update Atom? They deprecated things in 1.13.x which is why we pushed the update(s) earlier this month.

Related: #28
