### ISSUE TITLE
Preview while dragging

### ISSUE THREAD

**Issue by janstieler** [geoffthibeau/simple-drag-drop-text#31]
Hi,

I would appreciate if the package would serve a preview of the text while I'm on dragging.

Cheers

**Comment by Lotharyx** [comment]
Agree; there should be a preview, or if that's prohibitively complicated, some sort of change in the cursor to indicate the drag is in progress.  Most editors at least change the mouse cursor in some way.

**Comment by geoffthibeau** [comment]
@Lotharyx I've pushed a release to support cursor changes based on dragging or copying. Related: #10 .

I may need help with the preview feature if that's something you'd like to PR.

**Comment by geoffthibeau** [comment]
Regarding the preview, I am sunsetting this plugin to coincide with [Github's plan to sunset Atom by the end of this year](https://github.blog/2022-06-08-sunsetting-atom/). New features will not be added.
