### ISSUE TITLE
Plugin broken in Atom 1.21.0-beta0

### ISSUE THREAD

**Issue by alexdevero** [geoffthibeau/simple-drag-drop-text#34]
Plugin no longer works in the latest Atom 1.21.0-beta0. Selecting and then pasting text doesn't drag the text. Instead, the selection is changed. There is no error in console.

Atom version: 1.21.0-beta0
Plugin version: 0.3.4
OS: Windows 10 (64bit)

**Comment by zisheng-ai** [comment]
I hava same problem in 1.21.0-beta0. @alexdevero

**Comment by enoversum** [comment]
Here too!

**Comment by geoffthibeau** [comment]
Hey, thanks for the heads up. I've been working on a patch and will be releasing very soon.

**Comment by alexdevero** [comment]
@geoffthibeau Thank you very much Geoff!

**Comment by zisheng-ai** [comment]
First,Thanks for your patch.If you realease it,please tell us on here.

**Comment by geoffthibeau** [comment]
0.3.5 is also broken. I somehow missed two lines when copying over to the repo today.

0.3.6 is the version you want.

**Comment by zisheng-ai** [comment]
Good news in morning.
