### ISSUE TITLE
simple drag working anymore without CTRL since 0.5.0

### ISSUE THREAD

**Issue by franklinhardt** [geoffthibeau/simple-drag-drop-text#37]
simple draggin a selection without pressing any key stopped working since 0.5.0 It's working when CTRL is pressed, but this usually is intended to drag&copy the text instead of just dragging it. Had to install the old version to make it work again.

In Atom 1.39.1 x64 on Mac Mojave 10.14.5 (18F132)

**Comment by Bloemendaal** [comment]
~~Same problem here~~
Atom 1.39.1 on Windows 10

Edit: Change the delay in package settings :)

**Comment by geoffthibeau** [comment]
I added a feature to delay the drag in order to implement triple-click selections and another user's request to delay the drag. `500ms` is the default, but you're welcome to lower that to `1ms` within the plugin settings to simulate pre-0.5.0 behavior.

**Comment by franklinhardt** [comment]
Changing the delay to 1ms worked for me. thx!
