### ISSUE TITLE
dragging now just re-selects

### ISSUE THREAD

**Issue by mondeuse** [geoffthibeau/simple-drag-drop-text#38]
This package was working perfectly for ages, but something relatively recently has completely broken it for me. Now when I go to drag the selected text, the cursor just starts creating a new selection, rather than moving the text that was selected. I've tried disabling/restart Atom/re-enabling, uninstalling/restart Atom/re-installing, but no joy so far. Please help!
Running V1.40.1 on Win 10

**Comment by geoffthibeau** [comment]
@mondeuse `0.5.0` introduced a much-requested feature that changed the default behavior of this plugin. To restore pre-0.5.0 behavior, go to the plugin settings and drop the Delay down to 1ms.

**Comment by mondeuse** [comment]
Ah, I wasn't aware of that - have updated the settings as instructed and functionality is back, thank you!
