### ISSUE TITLE
Uncaught TypeError: Cannot read property 'classList' of undefined

### ISSUE THREAD

**Issue by Myvh** [geoffthibeau/simple-drag-drop-text#41]
Steps to reproduce:

1. Launch Atom with `simple-drag-drop-text` package enabled.
2. That's it.

**Atom**: 1.59.0 x64
**Electron**: 9.4.4
**OS**: Windows 10
**Thrown From**: [simple-drag-drop-text](https://github.com/geoffthibeau/simple-drag-drop-text) package 0.6.0

### Stack Trace

Uncaught TypeError: Cannot read property 'classList' of undefined

```
At C:\Users\Myvh773\.atom\packages\simple-drag-drop-text\lib\simple-drag-drop-text.js:298

TypeError: Cannot read property 'classList' of undefined
    at SimpleDragDropText.clear (/packages/simple-drag-drop-text/lib/simple-drag-drop-text.js:298:19)
    at /packages/simple-drag-drop-text/lib/simple-drag-drop-text.js:167:14
    at processTicksAndRejections (internal/process/task_queues.js:76:11)
```

### Commands

```
```

### Non-Core Packages

```
document-outline 2.1.2 
highlight-bad-chars-bl 1.4.3 
language-autohotkey2 1.0.1 
language-markdown 0.37.0 
markdown-writer 2.11.11 
open-recent 5.0.0 
simple-drag-drop-text 0.6.0 
tool-bar 1.4.4 
tool-bar-markdown-writer 0.5.1 
toolbar-custom 0.2.3 
```

**Comment by geoffthibeau** [comment]
👋 Thanks for reporting the bug so quickly.

This error wasn't happening during my testing, but 0.6.1 should resolve it.
