### ISSUE TITLE
Breaks Selecting multiple lines

### ISSUE THREAD

**Issue by jeffreydking** [geoffthibeau/simple-drag-drop-text#5]
Selecting multiple words still works fine (double clicking without a mouse up on the last click, then drag the cursor).

But selecting multiple lines no longer works with this package enabled (triple click without a mouse up on the third click, then drag the cursor). Rather than selecting a range of lines, it drags the word selected with the double click.

The package does not distinguish between a triple click and a double click followed by a click for dragging.

**Comment by mark-hahn** [comment]
> selecting multiple lines no longer works

Has it worked before?  I usually only drag words.

**Comment by jeffreydking** [comment]
It worked before I installed this package. I will often move blocks of code this way.

**Comment by ajoslin103** [comment]
yes, it's the triple-click and drag that is broken.

All the time I will triple-click a line and then drag-select to highlight & move a block of code.  But this package sees that as a double-click & click so it drags the word that I started on.

Interestingly, if you triple-click and hold you can see the whole line is selected -- but then when you drag it carries only the word you started on rather than extending the selection.

Hopefully it's an easy fix to bail out on a triple-click

al;

**Comment by ajoslin103** [comment]
What the!...  It was just broken again for one try (double-click and drag) I had just closed the settings dialog after the uninstall, restart, re-install & go to an open file and test it...  then I closed the settings and returned to tab I was working on and it didn't work first try - incredulously I tried again and it worked...  I still think it's something in the [state] defaults that gets overwritten after a successful drag.  

Or maybe it's that I'm triple-clicking by habit and not realizing it...

**Comment by ajoslin103** [comment]
I have found a work-around 

triple-click at the beginning or past the end of the line 

either one works as desired

**Comment by geoffthibeau** [comment]
I know this issue is old, but after triple-clicking to select a line and then click-dragging to move, it does seem to work as expected.

This may be a platform difference. I'm on Mac. @kingjeffrey can you confirm if this has been resolved?

**Comment by ajoslin103** [comment]
I think you are letting up on the mouse after your initial 3xClick 

The intention is to select multiple lines by starting w/a triple-click and then continuing with a drag

**Comment by mvanlammeren** [comment]
I would love to use this package, because I do occasionally drag text, but far more frequently I triple-click and drag to select blocks of text. I cannot use this package the way it is. I use a Mac, and triple-click and drag has been a UI element forever.

**Comment by geoffthibeau** [comment]
Resolved with v0.5.0.
2c75449e4924e08b30c40229916f49311a613aae
