### ISSUE TITLE
Drag text out of Atom

### ISSUE THREAD

**Issue by mickdekkers** [geoffthibeau/simple-drag-drop-text#9]
Would it be possible to add a feature that allows you to drag text out of Atom and into other applications?
Coming from Sublime, I am used to dragging and dropping text into Google Chrome for some quick searching.

**Comment by mark-hahn** [comment]
We would have to find out if electron can do this.  BTW, there is a package
to select text, hit a key, and start a search.

**Comment by mickdekkers** [comment]
I don't know how Sublime does it, but I found this .NET article: https://msdn.microsoft.com/en-us/library/bs2c4z53(v=vs.110).aspx

**Comment by mark-hahn** [comment]
>  I found this .NET article:

Unfortunately that is for windows apps, not the chrome browser.  I'll research using the browser.

I'm sorry for letting these issues drag out.  I've been busy with a startup but I'll force myself to get some time for this.

**Comment by mark-hahn** [comment]
I just searched for "drag items from chrome browser to another app" and got nothing.

**Comment by mickdekkers** [comment]
I found this Windows 10 article but I'm certain I was doing this in Windows 7 too: http://microsoft-news.com/windows-10-to-bring-drag-and-drop-capabilities-between-different-applications-and-more/

**Comment by mark-hahn** [comment]
> bring drag-and-drop functionality to Windows Runtime apps

Once again this pertains to windows apps, not a browser.  I can't code in windows.  If the browser doesn't already support this then I can't do it.  Also I would only do it if it can be cross-platform.  For example, I use linux, not windows.

**Comment by mickdekkers** [comment]
I see. I'm not using Linux; does it also allow dragging text between the browser and other applications?

**Comment by mark-hahn** [comment]
>  does it also allow dragging text between the browser and other
> applications?

I don't know. I didn't know you could do it on any OS.

 I just tried another google search on the topic with "chrome browser drag
text to os app" and I had a little more luck but nothing helpful.  It's
weird that based on these searches one would think it isn't possible
anywhere.  I'm gonna need some help to look into this any further.

**Comment by mickdekkers** [comment]
I made a gif to clarify what I mean:
![drag-drop-text-between-applications.gif](https://drive.google.com/uc?export=download&id=0BygQm6_xi9S9X1k1Vi1DQzRxeFU)

**Comment by mark-hahn** [comment]
Can you do me a favor and see if sublime supports this on anything other
than windows?  I can find references to dragging text between apps only for
.net and windows.  I looked in the sublime docs and couldn't find anything
about it.  I wanted to know if it was supported in Linux.

**Comment by mickdekkers** [comment]
I tried it in a fresh Ubuntu 15.10 Virtualbox VM with the default settings and it doesn't seem to support it.
I suppose it's possible a different desktop environment does support it, but like I said I don't use Linux so I wouldn't really know.

What's interesting is that Slack (an Electron application) _does_ support dragging text into other applications in Windows (but not into Slack from other applications).

**Comment by mark-hahn** [comment]
Unfortunately a technical question like this is too complex to do a real
google search on.  At least it was too complex for me.

**Comment by davidak** [comment]
Drag and drop from and to Sublime on OS X works. But that's a native app, Electron has to support it.

**Comment by geoffthibeau** [comment]
Enhancements to this plugin will not be added, as [Github has decided to sunset Atom by the end of this year](https://github.blog/2022-06-08-sunsetting-atom/).
